import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export const OPS_FILE = 'ops.json';
export const GENERATED_FILE = 'ops.generated.just';
export const RUNNER = 'scripts/op.mjs';

const ID_PATTERN = /^[a-z][a-z0-9-]*$/;

export function loadOps(root, opsPath) {
  const file = opsPath ?? join(root, OPS_FILE);
  return { file, data: JSON.parse(readFileSync(file, 'utf8')) };
}

export function validateShape(ops) {
  const errors = [];
  const ids = new Set();
  const operations = Array.isArray(ops.operations) ? ops.operations : null;
  if (!operations) {
    return { errors: [`${OPS_FILE} needs an operations array`], operations: [] };
  }
  for (const op of operations) {
    if (!ID_PATTERN.test(op.id ?? '')) errors.push(`operation id "${op.id}" is not kebab-case`);
    if (ids.has(op.id)) errors.push(`duplicate operation id "${op.id}"`);
    ids.add(op.id);
    const kind = op.kind ?? 'portable';
    if (kind !== 'portable' && kind !== 'twin') {
      errors.push(`operation "${op.id}" has unknown kind "${op.kind}"`);
    }
    if (kind === 'portable' && typeof op.run !== 'string') {
      errors.push(`portable operation "${op.id}" needs a run string`);
    }
    if (kind === 'twin') {
      if (!op.windows) errors.push(`twin operation "${op.id}" needs a windows implementation`);
      if (!op.posix) errors.push(`twin operation "${op.id}" needs a posix implementation`);
    }
  }
  return { errors, operations };
}

export function render(ops, options = {}) {
  const runner = options.runner ?? RUNNER;
  const lines = [
    '# Generated by scripts/op.mjs from ops.json. Do not edit.',
    '# Regenerate with: node scripts/op.mjs render',
    '',
    `op := "node ${runner}"`,
    '',
  ];
  for (const op of ops.operations ?? []) {
    const description = op.description ?? `Run the ${op.id} operation.`;
    const variadic = op.args ? ' *args' : '';
    const passthrough = op.args ? ' {{args}}' : '';
    lines.push(`# ${description}`);
    lines.push(`${op.id}${variadic}:`);
    lines.push(`    {{op}} run ${op.id}${passthrough}`);
    lines.push('');
  }
  return lines.join('\n');
}

export function interpreterFor(root, rel, args = []) {
  const full = join(root, rel);
  if (rel.endsWith('.ps1')) return { cmd: 'pwsh', argv: ['-NoLogo', '-NoProfile', '-File', full, ...args] };
  if (rel.endsWith('.sh')) return { cmd: 'bash', argv: [full, ...args] };
  if (/\.(mjs|js|cjs)$/.test(rel)) return { cmd: 'node', argv: [full, ...args] };
  return { cmd: full, argv: args };
}
